# Generated by Django 3.2.13 on 2022-05-25 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
                ('blood_group', models.CharField(max_length=124)),
                ('phone', models.IntegerField(max_length=10)),
                ('address', models.TextField(max_length=150)),
                ('mailid', models.CharField(max_length=150, unique=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='regapp.center')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='regapp.district')),
            ],
        ),
    ]
