# Generated by Django 3.2.5 on 2022-05-29 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regapp', '0003_auto_20220529_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='country',
            new_name='district',
        ),
    ]
